### ISSUE TITLE
[meta] Keyper benchmarking

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#357]
We want to have more empirical evidence, that the Keyper's Eon-DKG as well as the Epoch Key generation processes have reasonable performance and scalability.

For this, we require completion of the following child-issues *(to be refined)*:

- [ ] easier deployment of rolling-shutter software + environment (e.g. containerization, declarative environment)
- [ ] internal orchestration tooling to setup a staging / test environment
- [ ] distributed observability of processes (OpenTelemetry metrics and tracing)
- [ ] metrics accumulation, persistence and evaluation (Grafana etc.)
- [ ] benchmarking scenarios (stress-tests / external stimuli on the processes)
- [ ] P2P discovery - #353
