### ISSUE TITLE
Third party keyper setup

### ISSUE THREAD

**Issue by konradkonrad** [shutter-network/rolling-shutter#383]
We want to enable third parties to run a shutter keyper.

In order to make it accessible, we want to provide 
- [x] a pre-configured runtime setup (for the time being probably `docker compose`) #385
- [x] well documented configuration needs #386
- [x] well documented system requirements (CPU, RAM, storage, networking) #386 
- [x] bootnodes / seed nodes for joining the peer-to-peer networks #384
