### ISSUE TITLE
Distributed snapshutter setup

### ISSUE THREAD

**Issue by ulope** [shutter-network/rolling-shutter#532]
# Release checklist
- [ ] add LICENSEs everywhere
- [x] make https://github.com/shutter-network/snapshot-keyper public
- [x] make https://github.com/shutter-network/rolling-shutter/pkgs/container/snapshot-main public
- [x] make https://github.com/shutter-network/rolling-shutter/pkgs/container/snapshot-assets public
- [ ] tag release version for rolling-shutter repo
- [ ] tag release version for snapshot-main image
- [ ] Create genesis in `distributed-snapshutter` (see `RELEASE.md`)
- [ ] Collect keyper addresses from forum thread
- [ ] Ensure keyper set and collator in `play.json` for deployment is correct!
- [ ] deploy contracts from company owned key 
- [ ] tag release snapshot-assets image
- [ ] update image versions in snapshot-keyper repository
- [ ] tag release version for snapshot-keyper repository
- [ ] Stop test keypers
- [ ] Clean/restart the seed nodes: update the genesis file on seed nodes
- [ ] Run bootstrapping/genesis keyper to start shuttermint chain
- [ ] Publish the release!

# Questions
- [x] How do the keyper configs get generated?
- [x] Do we need to do anything about the public keys?

---
- [x] [multiple shuttermint nodes/production mode](https://github.com/shutter-network/rolling-shutter/issues/380)
---
- [ ] fix prometheus metrics
- [ ] store decryption key in snapshot db
- [ ] resend decryption keys on request
---
- [ ] test keyperset changes
- [ ] keyperset voting DKG
- [ ] active keyperset choice
- [x] Make eon id offset configurable
---
https://github.com/shutter-network/rolling-shutter/issues/383
- [x] [third party keyper runtime setup](https://github.com/shutter-network/rolling-shutter/issues/385)
- [x] [seed node hosting](https://github.com/shutter-network/rolling-shutter/issues/384)
- [ ] [on boarding documentation for keypers](https://github.com/shutter-network/rolling-shutter/issues/385)
---
Nice to haves:
- [ ] multiple(?)/failover safe "snapshot hubs"
- [ ] failover for `snapshot` command/interface
- [ ] authenticate jsonrpc requests (+"responses"?)
---
- [ ] switchover solution for new snapshot deployment

**Comment by LoringHarkness** [comment]
I'm updating the OKRs for Q4 2024, and this is one of them.
Which milestone(s) / tasks above are we aiming to reach / complete by end of October?
